"use client";

import { useState } from "react";
import { useSession } from "next-auth/react";
import { useRouter } from "next/navigation";
import Sidebar from "../../components/Sidebar";
import { Zap, Flame, Trash2, Send, CheckCircle } from "lucide-react";
import { submitEmission } from "./actions";

const SOURCES = [
  { value: "electricity", label: "TANGEDCO Electricity", unit: "kWh", icon: Zap, color: "#2563eb", desc: "Monthly electricity bill units from TANGEDCO" },
  { value: "diesel", label: "Diesel Generator", unit: "Liters", icon: Flame, color: "#ea580c", desc: "Fuel consumed by DG sets in liters" },
  { value: "canteen", label: "Canteen Waste", unit: "kg", icon: Trash2, color: "#16a34a", desc: "Solid waste generated by canteen in kg" },
];

const MONTHS = ["January","February","March","April","May","June","July","August","September","October","November","December"];
const FACTORS = { electricity: 0.82, diesel: 2.68, canteen: 2.5 };
const BUILDINGS = ["Main Block","Mechanical Block","EEE Block","ECE Block","CSE/IT Block","AI & DS Block","Civil Block","MBA Block","Library","Canteen & Hostel","Generator Room","Admin Block"];

export default function CarbonEmissionPage() {
  const { data: session, status } = useSession({ required: true });
  const router = useRouter();
  const [source, setSource] = useState("electricity");
  const [amount, setAmount] = useState("");
  const [month, setMonth] = useState(new Date().getMonth() + 1);
  const [year, setYear] = useState(new Date().getFullYear());
  const [building, setBuilding] = useState("");
  const [notes, setNotes] = useState("");
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState(null);
  const [error, setError] = useState("");

  if (status === "loading") return <div style={{display:'flex',alignItems:'center',justifyContent:'center',height:'100vh',color:'var(--text-secondary)'}}>Loading...</div>;

  const preview = amount ? (parseFloat(amount) * FACTORS[source]).toFixed(2) : null;
  const currentSource = SOURCES.find(s => s.value === source);

  async function handleSubmit(e) {
    e.preventDefault();
    setLoading(true);
    setError("");
    const fd = new FormData();
    fd.append("type", source);
    fd.append("amount", amount);
    fd.append("month", month);
    fd.append("year", year);
    fd.append("building", building);
    fd.append("notes", notes);
    const res = await submitEmission(fd);
    setLoading(false);
    if (res.success) {
      setResult(res.calculated);
    } else {
      setError(res.error || "Failed to save.");
    }
  }

  if (result !== null) {
    return (
      <div className="app-shell">
        <Sidebar user={session?.user} />
        <main className="main-content">
          <div style={{display:'flex',alignItems:'center',justifyContent:'center', minHeight:'70vh', flexDirection:'column', gap:'1.5rem', textAlign:'center'}}>
            <CheckCircle size={64} color="var(--accent-green)" />
            <h2 style={{fontSize:'2rem'}}>Data Recorded Successfully!</h2>
            <div className="card" style={{padding:'2rem', maxWidth:'400px'}}>
              <p className="text-secondary">Calculated CO₂e Emission</p>
              <p style={{fontSize:'3rem', fontWeight:800, fontFamily:'Space Grotesk'}} className="text-gradient">
                {result.toFixed(2)} kg
              </p>
              <p className="text-secondary" style={{fontSize:'0.85rem', marginTop:'0.5rem'}}>= {(result/1000).toFixed(4)} tonnes CO₂ equivalent</p>
            </div>
            <div style={{display:'flex',gap:'1rem'}}>
              <button className="btn-primary" onClick={() => { setResult(null); setAmount(""); setNotes(""); }}>
                + Log Another
              </button>
              <a href="/analytics" className="btn-secondary">View Analytics</a>
            </div>
          </div>
        </main>
      </div>
    );
  }

  return (
    <div className="app-shell">
      <Sidebar user={session?.user} />
      <main className="main-content animate-fade-in">
        <div className="page-header">
          <h1 className="page-title">Carbon Emission Entry</h1>
          <p className="page-subtitle">Log electricity, diesel, or canteen waste data to track campus CO₂ footprint</p>
        </div>

        {error && <div className="alert alert-error">{error}</div>}

        <form onSubmit={handleSubmit}>
          {/* Source Selection */}
          <div className="form-section delay-1 animate-fade-in">
            <h3>1. Select Emission Source</h3>
            <div style={{display:'grid', gridTemplateColumns:'repeat(auto-fit,minmax(200px,1fr))', gap:'1rem'}}>
              {SOURCES.map(s => (
                <div
                  key={s.value}
                  onClick={() => setSource(s.value)}
                  style={{
                    border: `2px solid ${source === s.value ? s.color : 'var(--border-color)'}`,
                    borderRadius:'12px',
                    padding:'1.2rem',
                    cursor:'pointer',
                    background: source === s.value ? `rgba(${s.color === '#2563eb' ? '37,99,235' : s.color === '#ea580c' ? '234,88,12' : '22,163,74'},0.05)` : '#fff',
                    transition:'all 0.2s',
                    display:'flex', flexDirection:'column', gap:'0.5rem'
                  }}
                >
                  <s.icon size={24} color={s.color} />
                  <strong style={{fontSize:'0.95rem'}}>{s.label}</strong>
                  <span style={{fontSize:'0.8rem', color:'var(--text-secondary)'}}>{s.desc}</span>
                  <span className="alert alert-info" style={{padding:'3px 8px', borderRadius:'6px', fontSize:'0.75rem', marginTop:'0.2rem'}}>Unit: {s.unit}</span>
                </div>
              ))}
            </div>
          </div>

          {/* Data Entry */}
          <div className="form-section delay-2 animate-fade-in">
            <h3>2. Enter Measurement Data</h3>
            <div className="form-grid">
              <div className="form-group">
                <label>Amount ({currentSource?.unit})*</label>
                <input
                  type="number"
                  step="0.01"
                  min="0"
                  value={amount}
                  onChange={e => setAmount(e.target.value)}
                  className="input-field"
                  placeholder={`e.g. ${source === 'electricity' ? '5000' : source === 'diesel' ? '200' : '150'}`}
                  required
                />
                {preview && (
                  <div className="alert alert-info" style={{marginTop:'0.5rem', fontSize:'0.85rem'}}>
                    ≈ <strong>{preview} kg CO₂e</strong> ({(parseFloat(preview)/1000).toFixed(4)} tonnes)
                  </div>
                )}
              </div>

              <div className="form-group">
                <label>Building / Location</label>
                <select value={building} onChange={e => setBuilding(e.target.value)} className="input-field">
                  <option value="">-- Select Building --</option>
                  {BUILDINGS.map(b => <option key={b} value={b}>{b}</option>)}
                </select>
              </div>

              <div className="form-group">
                <label>Month*</label>
                <select value={month} onChange={e => setMonth(Number(e.target.value))} className="input-field" required>
                  {MONTHS.map((m, i) => <option key={m} value={i+1}>{m}</option>)}
                </select>
              </div>

              <div className="form-group">
                <label>Year*</label>
                <select value={year} onChange={e => setYear(Number(e.target.value))} className="input-field" required>
                  {[2023,2024,2025,2026].map(y => <option key={y} value={y}>{y}</option>)}
                </select>
              </div>

              <div className="form-group" style={{gridColumn:'1/-1'}}>
                <label>Notes / Remarks (optional)</label>
                <textarea value={notes} onChange={e => setNotes(e.target.value)} className="input-field" placeholder="e.g. Festival week with extra generator usage..." rows={3} />
              </div>
            </div>
          </div>

          {/* CO2 Formula Reference */}
          <div className="form-section delay-3 animate-fade-in" style={{borderLeft:'4px solid var(--accent-orange)', background:'rgba(234,88,12,0.02)'}}>
            <h3>📐 CO₂e Calculation Reference</h3>
            <div style={{display:'grid', gridTemplateColumns:'repeat(auto-fit,minmax(200px,1fr))', gap:'0.8rem', marginTop:'0.8rem'}}>
              <div style={{background:'#f8fafc',padding:'0.8rem',borderRadius:'8px',fontSize:'0.85rem'}}>
                <strong style={{color:'#2563eb'}}>⚡ Electricity</strong><br/>
                Amount × 0.82 kg CO₂e/kWh<br/>
                <span style={{color:'var(--text-secondary)'}}>Indian grid emission factor</span>
              </div>
              <div style={{background:'#f8fafc',padding:'0.8rem',borderRadius:'8px',fontSize:'0.85rem'}}>
                <strong style={{color:'#ea580c'}}>🔥 Diesel</strong><br/>
                Amount × 2.68 kg CO₂e/L<br/>
                <span style={{color:'var(--text-secondary)'}}>IPCC standard combustion</span>
              </div>
              <div style={{background:'#f8fafc',padding:'0.8rem',borderRadius:'8px',fontSize:'0.85rem'}}>
                <strong style={{color:'#16a34a'}}>🗑 Canteen Waste</strong><br/>
                Amount × 2.5 kg CO₂e/kg<br/>
                <span style={{color:'var(--text-secondary)'}}>Mixed organic decomposition</span>
              </div>
            </div>
          </div>

          <button type="submit" className="btn-primary delay-4 animate-fade-in" style={{width:'100%',justifyContent:'center',padding:'1rem'}} disabled={loading}>
            <Send size={18} />
            {loading ? "Saving to database..." : "Submit Emission Record"}
          </button>
        </form>
      </main>
    </div>
  );
}
